spring.datasource.url=jdbc:mysql://localhost:3306/authapp 
spring.datasource.username=root
spring.datasource.password=Chirayu@1911
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# this is showing error into consloe.
logging.level.org.springframework.security=debug


# ===================================================================
# JWT SECURITY CONFIGURATION
# ===================================================================

# Secret Key used to sign the tokens (Base64 encoded)
jwt.secret-key=${JWT_SECRET_KEY:biwLlO+Ug7lwrBVHVlkAAUuKjSUrrWqokIXUoIbcMu4=}

# Access Token Time-to-Live (1 Hour = 3600000ms)
jwt.access-token-expiration-seconds=${JWT_ACCESS_EXPIRATION:3600}

# Refresh Token Time-to-Live (24 Hours = 86400000ms)
jwt.refresh-token-expiration-seconds=${JWT_REFRESH_EXPIRATION:86400}

# Identity of the token creator
jwt.issuer-name=${JWT_ISSUER:Chirayu_Auth_Service}

# Cookie Name for Refresh Token
jwt.refresh-token-cookie-name=${JWT_REFRESH_COOKIE_NAME:refreshToken}

# 1. Secure: Only send over HTTPS (Crucial for Prod)
# Set to false only for local localhost development if not using HTTPS
jwt.cookie.secure=${JWT_COOKIE_SECURE:true}

# 2. HttpOnly: Prevent JavaScript from accessing the cookie (XSS Protection)
jwt.cookie.http-only=${JWT_COOKIE_HTTP_ONLY:true}

# 3. SameSite: Protect against CSRF attacks
# Options: Strict, Lax, None
jwt.cookie.same-site=${JWT_COOKIE_SAME_SITE:Lax}
